on:
    workflow_dispatch:
        inputs:
            package_version:
                description: 'Package version to be published to NPM'
                required: true

name: Build Electron

jobs:
    prebuild-node:
        name: Upload Node Prebuild
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # using older ubuntu to mitigate "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found" error
                os: [ macos-latest, windows-2019, ubuntu-18.04 ]
        steps:
            -   uses: actions/checkout@v3
                with:
                    repository: "JoshuaWise/better-sqlite3"
            -   name: Use Node.js 18
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   run: npm install -g npm@6
            -   run: npm --version
            -   run: npm install && (npm list || true)
            -   name: Change package name
                # We're cloning better-sqlite3 here and republishing it under a different name (with prebuilt binaries).
                # Version is set manually, because sometimes we need to release new versions for the same version of better-sqlite3
                # major.minor should be kept. e.g. better-sqlite3@7.1.2 can be released as better-sqlite3-with-prebuilds 7.1.5,
                # but not 7.2.0.
                run: npx -y npe name "better-sqlite3-with-prebuilds" \
                    && npx -y npe repository.url "git+https://github.com/apify/better-sqlite3-with-prebuilds.git" \
                    && npx -y npe version "${{ github.event.inputs.package_version }}"
            -   name: Show package.json
                run: cat package.json
            -   name: Build release
                run: |
                    npx prebuild -r electron -t 16.0.0 -t 18.0.0 -t 20.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}

