on:
    workflow_dispatch:
        inputs:
            package_version:
                description: 'Package version to be published to NPM'
                required: true

name: Build-Alpine

jobs:
    prebuild-node:
        name: Upload Node Prebuild
        runs-on: ubuntu-latest

        container:
            image: node:18-alpine

        steps:
            -   uses: actions/checkout@v3
                with:
                    repository: "JoshuaWise/better-sqlite3"
            -   name: Install Make tools
                run: apk add --update --no-cache bash git openssh make cmake alpine-sdk
            -   name: Install Python
                run: apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            -   run: python --version
            -   name: Install packages
                run: npm install && npm list || true
            -   name: Change package name
                # We're cloning better-sqlite3 here and republishing it under a different name (with prebuilt binaries).
                # Version is set manually, because sometimes we need to release new versions for the same version of better-sqlite3
                # major.minor should be kept. e.g. better-sqlite3@7.1.2 can be released as better-sqlite3-with-prebuilds 7.1.5,
                # but not 7.2.0.
                run: npx -y npe name "better-sqlite3-with-prebuilds" \
                    && npx -y npe repository.url "git+https://github.com/apify/better-sqlite3-with-prebuilds.git" \
                    && npx -y npe version "${{ github.event.inputs.package_version }}"
            -   name: Show package.json
                run: cat package.json
            -   name: Build release
                run: |
                    npx -y detect-libc node ./node_modules/prebuild/bin.js -r node -t 16.0.0 -t 18.0.0 -t 20.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}
